language: python
python:
  - "2.7"
# command to install dependencies
services:
  - docker
before_install:
  - docker build -t cidc:flask .
# install:
#   - pip install -r requirements.txt
# # command to run tests
script:
  - python -m  pytest ./src/tests_square.py


before_deploy: "echo 'ready?'"

deploy:
  provider: s3
  access_key_id: "aws_access_key_id"
  secret_access_key: "aws_secret_access_key"
  bucket: test-priyam-cicd-bucket
  skip_cleanup: true

# after_deploy:
#   - ./after_deploy.sh


