language: python
python:
  - "2.7"
# command to install dependencies
services:
  - docker
before_install:
  - docker build -t cidc:flask .
# install:
#   - pip install -r requirements.txt
# # command to run tests
script:
  - python -m  pytest ./src/tests_square.py


before_deploy: "echo 'ready?'"

deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: test-priyam-cicd-bucket
  skip_cleanup: true
  acl: public_read
  region: "us-east-1"

# after_deploy:
#   - ./after_deploy.sh