name: Deploy to ec2

on:
  push:
    branches:
      - master

jobs:
  rsync_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get some info
        run: pwd & ls /home
      - name: scp into machine
        run: scp -r -i ${{secrets.ec2_pub}}  /home ec2-user@3.92.48.181:/home/ec2-user


