name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: contention/action-rsync-deploy@master
        with:
          args: -avzr --delete --exclude venv --exclude .git --exclude __pycache__ -i ${{ secrets.ec2_pub }} ec2-user@3.92.48.181:/home/ec2-user
        env: ${{ secrets.ec2_pub }}
    # - uses: actions/checkout@master
    # - uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --exclude '.git/*'
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
