name: Upload Website
on:
  push:
    branches:
    - master
jobs:
  build:
    name: testing
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        env:
          HOST: 3.92.48.181
          USERNAME: ec2-user
          KEY: ${{ secrets.ec2_pub }}
        with:
          source: ./
          target: /home/ec2-user
      - name: Hello, World in GitHub Actions
        run: echo 'Hello, World'
