# name: Deploy to ec2

# on:
#   push:
#     branches:
#       - master

# jobs:
#   rsync_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: get some info
#         run: pwd & ls /home
#       - name: scp into machine
#         env:
#           Deploy: ${{secrets.ec2_pub}}
#         run: scp -r -i $Deploy  /home ec2-user@3.92.48.181:/home/ec2-user



name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}