name: Upload Website
on:
  push:
    branches:
    - master
jobs:
  build:
    name: testing
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Run shell commands
        run: |
            pwd
            ls /home
      - name: Hello, World in GitHub Actions
        run: echo 'Hello, World'
        
