name: Upload Website
on:
  push:
    branches:
    - master
jobs:
  build:
    name: testing
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Run shell commands
        env:
          DEPLOY:${{ secrets.ec2_pub }}
        run: |
            pwd
            ls /home
            scp -r -i  $DEPLOY ./ ec2-user@3.92.48.181:/home/ec2-user
      - name: Hello, World in GitHub Actions
        run: echo 'Hello, World'
        
