name: Deploy to ec2

on:
  push:
    branches:
      - master

jobs:
  rsync_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: config and run
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.ec2_pub}}
        with:
          flags: '-avzr --delete'
          options: '--exclude venv'
          ssh_options: ''
          src: './'
          dest: 'ec2-user@3.92.48.181:/home/ec2-user'
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
